version: '3.3'
services:
  api:
    build: .
    env_file: .env
    ports:
      - 3000:3000

  mongodb:
    image: mongo 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - mongo-db:/data/db
    ports:
      - '27017:27017'    
      
volumes:
  mongo-db: